### Exercice 1 
1. Construire une liste liste1 qui contient les nombres de 1 à 99 inclus (avec la fonction range).
2. Ajouter à l’aide d’une boucle les éléments de 100 à 199, à une liste vide liste2.
3. En une opération, ajouter tous les éléments de la liste liste2 à la liste liste1.

In [93]:
liste1 = [i for i in range(1,100)]
print("Liste 1 : \n" + str(liste1) + "\n")
liste2 = [i for i in range(100,200)]
print("Liste 2 : \n" + str(liste2) + "\n")
liste1 += liste2
print("Liste 1 après concaténation de liste 2 \n" + str(liste1)+"\n")

Liste 1 :
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

Liste 2 :
[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]

Liste 1 après concaténation de liste 2
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]

4. Avec la fonction range(), construire une liste3 composée de tous les nombres pairs de 0 à 100
(inclus).
5. À l’aide d’une boucle supprimez tous les multiples de 10 contenus dans la liste liste3.
6. Affichez la longueur de la liste liste3.
7. Affichez tous les multiples de 8 de liste3.
8. Affichez les 20 premiers éléments de la liste liste3 (sans faire de boucle).
9. Affichez les éléments suivants les 20 premiers éléments de liste3.
10. Affichez les 10 derniers éléments de liste3.

In [96]:
liste3 = [i for i in range(0, 101, 2)]
print("Liste 3 (nombres pairs de 0 à 100) : \n" + str(liste3) + "\n")

liste3 = [i for i in liste3 if i % 10 != 0]
print("Liste 3 après suppression des multiples de 10 : \n" + str(liste3) + "\n")

print("Longueur de liste 3 : " + str(len(liste3)) + "\n")

print("Les multiples de 8 dans liste 3 sont :")
print(str([i for i in liste3 if i % 8 == 0]) + "\n")

print("Les 20 premiers termes de liste 3 sont :")
print(str(liste3[:20])+"\n")

print("Les éléments suivants les 20 premiers éléments de liste3 sont :")
print(str(liste3[20:])+"\n")
print("Les 10 derniers éléments de liste 3 sont :")
print(str(liste3[-10:])+"\n")

Liste 3 (nombres pairs de 0 à 100) :
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]

Liste 3 après suppression des multiples de 10 :
[2, 4, 6, 8, 12, 14, 16, 18, 22, 24, 26, 28, 32, 34, 36, 38, 42, 44, 46, 48, 52, 54, 56, 58, 62, 64, 66, 68, 72, 74, 76, 78, 82, 84, 86, 88, 92, 94, 96, 98]

Longueur de liste 3 : 40

Les multiples de 8 dans liste 3 sont :
[8, 16, 24, 32, 48, 56, 64, 72, 88, 96]

Les 20 premiers termes de liste 3 sont :
[2, 4, 6, 8, 12, 14, 16, 18, 22, 24, 26, 28, 32, 34, 36, 38, 42, 44, 46, 48]

Les éléments suivants les 20 premiers éléments de liste3 sont :
[52, 54, 56, 58, 62, 64, 66, 68, 72, 74, 76, 78, 82, 84, 86, 88, 92, 94, 96, 98]

Les 10 derniers éléments de liste 3 sont :
[76, 78, 82, 84, 86, 88, 92, 94, 96, 98]

11. Créer une liste4 composée uniquement des nombres impairs jusqu’à 50 en une ligne.
12. On dispose de la liste de mots suivantes :
listW ords = [”hello”, ”the”, ”world”, ”apple”, ”tree”, ”lemon”].
En une seule ligne de code, créez une nouvelle liste contenant les mots de listW ords de moins
de 5 lettres.
13. Construire une liste5 contenant les 20 premiers termes de la suite de Fibonacci. La suite
de Fibonacci (Fn)n∈N est définie par F0 = 0, F1 = 1, et la relation de récurrence Fn =
Fn−1 + Fn−2 pour n ≥ 2.
14. Créer une liste6 avec les valeurs [1,2,3] puis créer une copie de liste6 dans une liste6bis
(attention si on change une valeur de liste6bis, la liste6 ne doit pas être modifiée). cf.
fonction copy().

In [99]:
liste4 = [i for i in range(0, 51) if i % 2 == 0]
print("Liste 4 (nombres pairs de 0 à 50) : \n" + str(liste4) + "\n")

listWords = ["hello", "the", "world", "apple", "tree", "lemon"]
listWords5 = [w for w in listWords if len(w) < 5]
print("Liste des mots de moins de 5 caractères : \n" + str(listWords5) + "\n")

liste5 = [0, 1]
for k in range(2, 20):
    liste5.append(liste5[k - 1] + liste5[k - 2])
print("Liste Fibonacci jusqu'au vingtième terme : \n" + str(liste5) + "\n")

liste6 = [1, 2, 3]
liste6bis = liste6.copy()
liste6bis.append(1)
print("Liste 6 originale : \n" + str(liste6) + "\n")
print("Copie de liste 6 après ajout d'un élément dans celle-ci : \n" + str(liste6bis) + "\n")

Liste 4 (nombres pairs de 0 à 50) :
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]

Liste des mots de moins de 5 caractères :
['the', 'tree']

Liste Fibonacci jusqu'au vingtième terme :
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]

Liste 6 originale :
[1, 2, 3]

Copie de liste 6 après ajout d'un élément dans celle-ci :
[1, 2, 3, 1]

### Exerice 2
1. Importer la librairie NumPy.
2. Créer un numpy array de dimension 1 et de taille 10 contenant toujours la valeur 0.
3. Créer un numpy array de dimension 1 et de taille 10 contenant toujours la valeur 1.
4. Créer un numpy array de dimension 1 et de taille 10 contenant toujours la valeur 5.
5. Créer un numpy array tab1 de dimension 1 contenant tous les nombres de 1 à 10 avec un pas
de 0.5.
6. Créer un numpy array tab2 de dimension 1 avec les entiers de 10 à 30

In [102]:
import numpy as np
np.random.seed(0)

zeros = np.zeros(10)
print("Tableau de 10 zéros : \n" + str(zeros) + "\n")

ones = np.ones(10)
print("Tableau de 10 uns : \n" + str(ones) + "\n")

fives = 5 * np.ones(10)
print("Tableau de 10 fois 5 : \n" + str(fives) + "\n")

tab1 = np.arange(1, 10.5, 0.5)
print("Tableau de 1 à 10 avec un pas de 0.5 : \n" + str(tab1) + "\n")

tab2 = np.arange(10, 31)
print("Tableau allant de 10 à 30 : \n" + str(tab2) + "\n")

Tableau de 10 zéros :
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Tableau de 10 uns :
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Tableau de 10 fois 5 :
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

Tableau de 1 à 10 avec un pas de 0.5 :
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]

Tableau allant de 10 à 30 :
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]

7. Calculer la somme des entiers de tab2 (une seule ligne).
8. Calculer la moyenne des entiers de tab2 (une seule ligne).
9. Créer un vecteur tab3 de même dimension que tab2 contenant des valeurs aléatoires et
effectuer le produit scalaire des vecteurs tab2 et tab3.
10. Sélectionner les éléments de tab2 dont la valeur est supérieure à 20.
11. Sélectionner les éléments en position 1, 5, 10 et 15 de tab2.
12. Générer une matrice identité de taille 9 (voir la fonction eye de la librairie numpy).
13. Créer un numpy array de dimension 2 et de taille 10 × 10 contenant toujours la valeur 1.
14. Afficher les dimentions de la matrice précédente.
15. Créer un numpy array de dimension 1 avec les valeurs de 0 à 8 et le transformer en matrice
3 × 3

In [105]:
print("Somme de tab2 : " + str(tab2.sum()))
print("Moyenne de tab2 : " + str(tab2.mean()) + "\n")

tab3 = np.random.randn(tab2.shape[0])
scal = tab2.dot(tab3)
print("Produit scalaire entre tab2 et tab3 : \n" + str(scal) + "\n")

print("Éléments de tab2 supérieurs ou égaux à 20 : \n" + str([int(i) for i in tab2 if i >= 20]) + "\n")
print("Éléments de tab2 aux indices [1, 5, 10, 15] : \n" + str([tab2[i] for i in [1, 5, 10, 15]]) + "\n")

id9 = np.eye(9)
print("Matrice identité 9x9 : \n" + str(id9) + "\n")

ones10 = np.ones([10, 10])
print("Matrice 10x10 remplie de uns : \n" + str(ones10) + "\n")
print("Dimensions de la matrice ones10 : " + str(ones10.shape) + "\n")

tab4 = np.arange(0, 9)
tab4 = tab4.reshape(3, 3)
print("Tableau 3x3 : \n" + str(tab4) + "\n")

Somme de tab2 : 420
Moyenne de tab2 : 20.0

Produit scalaire entre tab2 et tab3 :
105.64789184258072

Éléments de tab2 supérieurs ou égaux à 20 :
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

Éléments de tab2 aux indices [1, 5, 10, 15] :
[11, 15, 20, 25]

Matrice identité 9x9 :
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]

Matrice 10x10 remplie de uns :
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Dimensions de la matrice ones10 : (10, 10)

Tableau 3x3 :
[[0 1 2]
 [3 4 5]
 [6 7 8]]

16. Créer la matrice A suivante :
0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1
0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2
0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3
0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4
0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5
0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6
0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8
0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9
0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.0
17. Extraire la matrice B suivante de la matrice A précédente :
0.61 0.62 0.63 0.64
0.71 0.72 0.73 0.74
0.81 0.82 0.83 0.84
0.91 0.92 0.93 0.94
18. Générer une matrice de 1 de la taille de la matrice B.
19. Extraire la matrice C suivante de la matrice A :
0.21 0.23 0.25 0.27
0.31 0.33 0.35 0.37
20. Calculer le produit matriciel entre la matrice C et la matrice B.
21. Récupérer la valeur 0.55 dans la matrice A.
2
22. Récupérer la 4ème colonne de la matrice A
23. Récupérer la 4ème ligne de la matrice A
24. Récupérer une sous-matrice de la matrice A en ne gardant que les lignes telles que la valeur
de la colonne 4 est supérieure à 0.5
25. Calculer la moyenne globale de cette matrice A.
26. Calculer la moyenne de chaque ligne de la matrice A.
27. Calculer la moyenne de chaque colonne de la matrice A.
28. Calculer le produit scalaire de la première colonne de la matrice A avec la première ligne de
la matrice A.
29. Remplacer le centre de la matrice par la valeur 0 comme l'exemple suivant :
0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1
0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2
0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3
0.31 0.32 0.33 0 0 0 0 0.38 0.39 0.4
0.41 0.42 0.43 0 0 0 0 0.48 0.49 0.5
0.51 0.52 0.53 0 0 0 0 0.58 0.59 0.6
0.61 0.62 0.63 0 0 0 0 0.68 0.69 0.7
0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8
0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9
0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.0
30. Récupérer les index auxquels sont situées les valeurs 0.

In [108]:
A = np.round(np.linspace(0.01, 1, 100), 2).reshape(10, 10)
print("Matrice A 10x10 : \n" + str(A) + "\n")

B = A[6:, :4]
print("Sous-matrice B extraite de A : \n" + str(B) + "\n")

Bbis = np.ones(B.shape)
print("Matrice Bbis remplie de uns : \n" + str(Bbis) + "\n")

C = np.array([float(A[i][j]) for i in range(2, 4) for j in range(0, 7, 2)]).reshape(2, 4)
print("Matrice C extraite de A : \n" + str(C) + "\n")

scal2 = C.dot(B)
print("Produit scalaire entre C et B : \n" + str(scal2) + "\n")

v = A[A == 0.55]
print("Valeurs de A égales à 0.55 : \n" + str(v) + "\n")

A4C = A[:, 3]
print("Colonne 4 de A : \n" + str(A4C) + "\n")

A4L = A[3, :]
print("Ligne 4 de A : \n" + str(A4L) + "\n")

subA = np.array([elt for elt in A if elt[4] > 0.5])
print("Sous-matrice avec éléments de la colonne 4 > 0.5 : \n" + str(subA) + "\n")

avgA = A.mean()
print("Moyenne de tous les éléments de A : " + str(avgA) + "\n")

avgAL = A.mean(0)
print("Moyenne des colonnes de A : \n" + str(avgAL) + "\n")

avgAC = A.mean(1)
print("Moyenne des lignes de A : \n" + str(avgAC) + "\n")

subscalA = A[0, :].dot(A[:, 0])
print("Produit scalaire entre la première ligne et la première colonne de A : " + str(subscalA) + "\n")

A[3:7, 3:7] = 0
print("Matrice A après modification : \n" + str(A) + "\n")

pos0A = np.argwhere(A == 0)
print("Indices des éléments égaux à 0 dans A : \n" + str(pos0A) + "\n")

Matrice A 10x10 :
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]

Sous-matrice B extraite de A :
[[0.61 0.62 0.63 0.64]
 [0.71 0.72 0.73 0.74]
 [0.81 0.82 0.83 0.84]
 [0.91 0.92 0.93 0.94]]

Matrice Bbis remplie de uns :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Matrice C extraite de A :
[[0.21 0.23 0.25 0.27]
 [0.31 0.33 0.35 0.37]]

Produit scalaire entre C et B :
[[0.7396 0.7492 0.7588 0.7684]
 [1.0436 1.0572 1.0708 1.0844]]

Valeurs de A égales à 0.55 :
[0.55]

Colonne 4 de A :
[0.04 0.14 0.24 0.34 0.44 0.54 0.64 0.74 0.84 0.94]

Ligne 4 de A :
[0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]

Sous-matrice avec éléments de la colonne 4 > 0.5 :
[[0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]

Moyenne de tous les éléments de A : 0.505

Moyenne des colonnes de A :
[0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55]

Moyenne des lignes de A :
[0.055 0.155 0.255 0.355 0.455 0.555 0.655 0.755 0.855 0.955]

Produit scalaire entre la première ligne et la première colonne de A : 0.3355

Matrice A après modification :
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.   0.   0.   0.   0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.   0.   0.   0.   0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.   0.   0.   0.   0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.   0.   0.   0.   0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]

Indices des éléments égaux à 0 dans A :
[[3 3]
 [3 4]
 [3 5]
 [3 6]
 [4 3]
 [4 4]
 [4 5]
 [4 6]
 [5 3]
 [5 4]
 [5 5]
 [5 6]
 [6 3]
 [6 4]
 [6 5]
 [6 6]]